version: '3'
services:
  server:
    container_name: doodle_server 
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    depends_on:
      - db
    restart: on-failure
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/doodledb?schema=public
      ACCESS_TOKEN_SECRET: "random1234wordrandom"
  client:
    container_name: doodle_client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: on-failure

  db:
    container_name: doodle_db
    image: postgres:15
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: doodledb
    volumes:
      - pg_data:/var/lib/postgresql
volumes:
  pg_data: {}