apiVersion: v1
kind: Service
metadata:
  name: doodle-client
spec:
  type: LoadBalancer
  selector:
    app: doodle-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
