apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    service: postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    service: postgres
  type: ClusterIP