apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: doodle-db
spec:
  serviceName: "doodle-db"
  replicas: 1
  selector:
    matchLabels:
      app: doodle-db
  template:
    metadata:
      labels:
        app: doodle-db
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: doodle-secret
              key: postgres-password
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_DB
          value: "doodledb"
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: pgdata
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
